"""Add marketplace tables

Revision ID: 27e85a258187
Revises:
Create Date: 2026-03-04 23:56:50.876891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27e85a258187"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "marketplace_plugins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("homepage_url", sa.Text(), nullable=True),
        sa.Column("repository_url", sa.Text(), nullable=True),
        sa.Column("license", sa.String(length=50), nullable=True),
        sa.Column("downloads", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_plugins_category", "marketplace_plugins", ["category"])
    op.create_index("idx_plugins_tags", "marketplace_plugins", ["tags"], postgresql_using="gin")
    op.create_index(
        op.f("ix_marketplace_plugins_name"), "marketplace_plugins", ["name"], unique=True
    )

    op.create_table(
        "marketplace_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plugin_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("changelog", sa.Text(), nullable=True),
        sa.Column("package_url", sa.Text(), nullable=False),
        sa.Column("package_hash", sa.String(length=64), nullable=False),
        sa.Column("package_size", sa.BigInteger(), nullable=True),
        sa.Column("min_netkitx_version", sa.String(length=50), nullable=True),
        sa.Column("max_netkitx_version", sa.String(length=50), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("yanked", sa.Boolean(), nullable=False, server_default="false"),
        sa.ForeignKeyConstraint(["plugin_id"], ["marketplace_plugins.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_versions_plugin", "marketplace_versions", ["plugin_id"])
    op.create_index(
        "idx_versions_plugin_version", "marketplace_versions", ["plugin_id", "version"], unique=True
    )

    op.create_table(
        "marketplace_dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("depends_on_plugin", sa.String(length=255), nullable=False),
        sa.Column("version_constraint", sa.String(length=100), nullable=False),
        sa.Column("optional", sa.Boolean(), nullable=False, server_default="false"),
        sa.ForeignKeyConstraint(["version_id"], ["marketplace_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_deps_version", "marketplace_dependencies", ["version_id"])

    op.create_table(
        "user_installed_plugins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plugin_name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("installed_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_installed_user", "user_installed_plugins", ["user_id"])
    op.create_index(
        "idx_user_installed_unique",
        "user_installed_plugins",
        ["user_id", "plugin_name"],
        unique=True,
    )

    op.create_table(
        "marketplace_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plugin_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name="check_rating_range"),
        sa.ForeignKeyConstraint(["plugin_id"], ["marketplace_plugins.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_reviews_plugin", "marketplace_reviews", ["plugin_id"])
    op.create_index(
        "idx_reviews_unique", "marketplace_reviews", ["plugin_id", "user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_reviews_unique", table_name="marketplace_reviews")
    op.drop_index("idx_reviews_plugin", table_name="marketplace_reviews")
    op.drop_table("marketplace_reviews")

    op.drop_index("idx_user_installed_unique", table_name="user_installed_plugins")
    op.drop_index("idx_user_installed_user", table_name="user_installed_plugins")
    op.drop_table("user_installed_plugins")

    op.drop_index("idx_deps_version", table_name="marketplace_dependencies")
    op.drop_table("marketplace_dependencies")

    op.drop_index("idx_versions_plugin_version", table_name="marketplace_versions")
    op.drop_index("idx_versions_plugin", table_name="marketplace_versions")
    op.drop_table("marketplace_versions")

    op.drop_index(op.f("ix_marketplace_plugins_name"), table_name="marketplace_plugins")
    op.drop_index("idx_plugins_tags", table_name="marketplace_plugins", postgresql_using="gin")
    op.drop_index("idx_plugins_category", table_name="marketplace_plugins")
    op.drop_table("marketplace_plugins")
    # ### end Alembic commands ###
